name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Download Setup Tool
        run: Invoke-WebRequest https://github.com/Personal-Cloud/PersonalCloudSetup/releases/download/v1.4/PersonalCloudSetup.zip -Out .\PersonalCloudSetup.zip

      - name: Extract Setup Tool
        run: Expand-Archive -Path .\PersonalCloudSetup.zip -DestinationPath .\PersonalCloudSetup

      - name: Get Version String
        uses: frabert/replace-string-action@master
        id: get-version-string
        with:
          pattern: 'v(.*)'
          string: "${{ event.release.tag_name }}"
          replace-with: '$1'
          flags: 'g'

      - name: Run Setup Tool
        run: .\PersonalCloudSetup\PersonalCloudSetup.exe -d .\PersonalCloudSetup\Data -b "${{ steps.get-version-string.outputs.replaced }}"
        
